# Generated by Django 2.1.7 on 2019-04-10 17:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='club_avatars')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='club_banners')),
                ('description', models.CharField(max_length=8000)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClubEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nudge.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=8000)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Member', max_length=200)),
                ('perms', models.BooleanField(default=False)),
                ('invite_reason', models.CharField(max_length=64)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nudge.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='user_banners')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='nudge.Profile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nudge.Profile'),
        ),
        migrations.AddField(
            model_name='clubevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nudge.Event'),
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(through='nudge.ClubEvents', to='nudge.Event'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='nudge.Membership', to='nudge.Profile'),
        ),
    ]
